package com.localsync.service;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.localsync.model.Device;
import com.localsync.model.Permission;
import com.localsync.model.Session;
import com.localsync.repository.DeviceRepository;
import com.localsync.repository.SessionRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@Service
@RequiredArgsConstructor
@Slf4j
public class PairingService {

    private final DeviceRepository deviceRepository;
    private final SessionRepository sessionRepository;
    private final JwtService jwtService;
    private final TunnelService tunnelService;

    @Value("${localsync.jwt.secret}")
    private String secret;

    @Value("${localsync.qr.expiry-seconds:300}")
    private long qrExpirySeconds;

    // In-memory pending QR tokens: token -> expiry timestamp
    private final Map<String, Long> pendingQrTokens = new ConcurrentHashMap<>();

    /**
     * Generate a QR code image (base64 PNG) for device pairing.
     * Encodes both LAN address and Remote Internet Gateway for anywhere access!
     */
    public Map<String, String> generateQrCode() throws WriterException, IOException {
        String token = UUID.randomUUID().toString();
        long expiry = System.currentTimeMillis() + (qrExpirySeconds * 1000);
        String hmac = computeHmac(token + ":" + expiry);

        pendingQrTokens.put(token, expiry);

        String host = tunnelService.getLocalIpAddress();
        String localUrl = tunnelService.getLocalUrl();
        String remoteUrl = tunnelService.getRemoteUrl() != null ? tunnelService.getRemoteUrl() : "";

        String qrContent = String.format(
            "localsync://pair?token=%s&host=%s&port=8080&sig=%s&exp=%d&localUrl=%s&remoteUrl=%s",
            token, host, hmac, expiry, localUrl, remoteUrl
        );

        // Generate QR image
        QRCodeWriter qrWriter = new QRCodeWriter();
        Map<EncodeHintType, Object> hints = new EnumMap<>(EncodeHintType.class);
        hints.put(EncodeHintType.MARGIN, 1);
        BitMatrix bitMatrix = qrWriter.encode(qrContent, BarcodeFormat.QR_CODE, 300, 300, hints);

        ByteArrayOutputStream pngOut = new ByteArrayOutputStream();
        MatrixToImageWriter.writeToStream(bitMatrix, "PNG", pngOut);
        String base64 = Base64.getEncoder().encodeToString(pngOut.toByteArray());

        return Map.of(
            "qrImage", "data:image/png;base64," + base64,
            "token", token,
            "expiresAt", String.valueOf(expiry),
            "exp", String.valueOf(expiry),
            "sig", hmac,
            "host", host,
            "localUrl", localUrl,
            "remoteUrl", remoteUrl
        );
    }

    /**
     * Validate a QR token sent from the phone and issue a JWT.
     */
    @Transactional
    public Map<String, String> pairDevice(String token, String hmac, long expiry,
                                          String deviceName, String deviceType, String deviceIp) {

        // Check expiry (allow 60s clock skew)
        if (System.currentTimeMillis() > (expiry + 60000L)) {
            throw new RuntimeException("QR code expired. Please click Refresh on your laptop screen.");
        }

        // Verify HMAC signature (proves the QR code was genuinely generated by this server)
        String expectedHmac = computeHmac(token + ":" + expiry);
        if (!expectedHmac.equals(hmac)) {
            throw new RuntimeException("Invalid QR signature. Please refresh the QR code.");
        }

        // Clean up pending token if present
        pendingQrTokens.remove(token);

        // Clean up duplicate devices with same name or untrusted devices
        List<Device> existingDevs = deviceRepository.findAll();
        for (Device d : existingDevs) {
            if (deviceName.equalsIgnoreCase(d.getDeviceName()) || !d.isTrusted()) {
                try {
                    deviceRepository.delete(d);
                } catch (Exception ignored) {}
            }
        }

        // Create device with persistent deviceToken (1-year validity)
        String deviceId = UUID.randomUUID().toString();
        String deviceToken = UUID.randomUUID().toString() + "-" + UUID.randomUUID().toString();
        LocalDateTime tokenExpiry = LocalDateTime.now().plusYears(1);

        Device device = Device.builder()
            .deviceId(deviceId)
            .deviceName(deviceName)
            .deviceType(deviceType)
            .ipAddress(deviceIp)
            .lastSeenIp(deviceIp)
            .pairedAt(LocalDateTime.now())
            .lastSeen(LocalDateTime.now())
            .trusted(true)
            .fingerprint(UUID.randomUUID().toString())
            .deviceToken(deviceToken)
            .deviceTokenExpiry(tokenExpiry)
            .permissions(new ArrayList<>())
            .sessions(new ArrayList<>())
            .build();

        // Default permissions: read-only on standard folders
        List<Permission> defaultPermissions = createDefaultPermissions(device);
        device.setPermissions(defaultPermissions);
        deviceRepository.save(device);

        // Issue JWT
        String jwt = jwtService.generateToken(deviceId, deviceName, Map.of("deviceType", deviceType));
        String sessionId = jwtService.extractJti(jwt);

        // Save session
        Session session = Session.builder()
            .sessionId(sessionId)
            .device(device)
            .createdAt(LocalDateTime.now())
            .expiresAt(null)  // permanent session
            .active(true)
            .ipAddress(deviceIp)
            .build();
        sessionRepository.save(session);

        String localUrl = tunnelService.getLocalUrl();
        String remoteUrl = tunnelService.getRemoteUrl() != null ? tunnelService.getRemoteUrl() : "";

        log.info("Device paired permanently: {} ({})", deviceName, deviceId);
        return Map.of(
            "token", jwt,
            "deviceToken", deviceToken,
            "deviceId", deviceId,
            "deviceName", deviceName,
            "localUrl", localUrl,
            "remoteUrl", remoteUrl
        );
    }

    /**
     * Seamless re-connection using persistent deviceToken (no QR re-scan needed).
     */
    @Transactional
    public Map<String, String> reconnect(String deviceToken, String clientIp) {
        Device device = deviceRepository.findByDeviceTokenAndTrustedTrue(deviceToken)
            .orElseThrow(() -> new RuntimeException("Device not recognized or untrusted"));

        if (device.getDeviceTokenExpiry() != null && device.getDeviceTokenExpiry().isBefore(LocalDateTime.now())) {
            throw new RuntimeException("Device pairing expired. Please re-pair with QR.");
        }

        device.setLastSeen(LocalDateTime.now());
        device.setLastSeenIp(clientIp);
        deviceRepository.save(device);

        String jwt = jwtService.generateToken(device.getDeviceId(), device.getDeviceName(), 
            Map.of("deviceType", device.getDeviceType() != null ? device.getDeviceType() : "android"));
        String sessionId = jwtService.extractJti(jwt);

        Session session = Session.builder()
            .sessionId(sessionId)
            .device(device)
            .createdAt(LocalDateTime.now())
            .expiresAt(null)
            .active(true)
            .ipAddress(clientIp)
            .build();
        sessionRepository.save(session);

        String localUrl = tunnelService.getLocalUrl();
        String remoteUrl = tunnelService.getRemoteUrl() != null ? tunnelService.getRemoteUrl() : "";

        log.info("Device auto-reconnected without QR: {} ({})", device.getDeviceName(), device.getDeviceId());
        return Map.of(
            "token", jwt,
            "deviceId", device.getDeviceId(),
            "deviceName", device.getDeviceName(),
            "localUrl", localUrl,
            "remoteUrl", remoteUrl
        );
    }

    private List<Permission> createDefaultPermissions(Device device) {
        String userHome = System.getProperty("user.home");
        List<String[]> defaults = List.of(
            new String[]{"Documents", userHome + "/Documents"},
            new String[]{"Downloads", userHome + "/Downloads"},
            new String[]{"Pictures", userHome + "/Pictures"},
            new String[]{"Videos", userHome + "/Videos"},
            new String[]{"Desktop", userHome + "/Desktop"}
        );
        List<Permission> permissions = new ArrayList<>();
        for (String[] entry : defaults) {
            permissions.add(Permission.builder()
                .device(device)
                .folderLabel(entry[0])
                .folderPath(entry[1])
                .canRead(true)
                .canWrite(false)
                .canDelete(false)
                .build());
        }
        return permissions;
    }

    private String computeHmac(String data) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(secret.getBytes(), "HmacSHA256"));
            return Base64.getUrlEncoder().encodeToString(mac.doFinal(data.getBytes()));
        } catch (Exception e) {
            throw new RuntimeException("HMAC computation failed", e);
        }
    }

    private String getLocalIpAddress() {
        try {
            return InetAddress.getLocalHost().getHostAddress();
        } catch (Exception e) {
            return "127.0.0.1";
        }
    }
}
